### -------- Armbruster2026_MapMyCellInputGeneration--------

Version: 2026-07-30


- In this script we loaded the raw count matrix of our annotated zebrafish CA clusters that we exported in "Script8_Armbruster2026_Preparation_for_MapMyCell" and change the zebrafish gene names into their respective mouse ortholog names based on orthology information from https://www.alliancegenome.org/downloads#orthology downladed in March 2025 (see Table S5A).

- Raw counts of zebrafish paralogous genes with a single suggested mouse homolog were summed up. 

- Then the renamed count matrix containing 1,922 cells and 11,490 genes was exported as csv file and forwarded to the browser-based version of MapMyCells (Allen Institute; RRID:SCR_024672).

- The session info including the used packages and their versions is provided at the end of this script.

# 1. Load packages

In [1]:
import pandas as pd
import session_info

# 2. Load data

- Loading the homology dataframe as well as the expression matrix of the cells as shown in Figure 7

In [2]:
homology_zf_mouse_df = pd.read_csv(r"D:\scRNAseq\10X\DA136\SeuratAnalysis_2024-09-03\Resources\zf10_zf11_mouse_gene_homologues_full.csv", sep=";")
expr_df = pd.read_csv(r"D:\scRNAseq\10X\DA136\SeuratAnalysis_2024-09-03\MapMyCells\MapMyCells_input_data\modified_expression_matrix_zebrafishnames.csv", index_col = 0)

In [3]:
expr_df[0:10]

,AAACCCACACTCCGGA_Hyp3,AAACCCATCTACTATC_Hb3,AAACGAAAGGCTTCCG_PrT,AAACGAACAAGTGCAG_pTub,AAACGAAGTCTCGGGT_vFb.Prog2,AAACGCTTCCCAGGCA_Hyp1,AAAGAACCAGAGTTCT_Cb,AAAGAACTCCATCGTC_vFb.Prog1,AAAGAACTCGAACGGA_vFb.Prog2,AAAGGATCACGACAGA_vFb.Prog2,...,TTTGATCCACGGTGAA_Hyp3,TTTGATCTCGCTTGAA_vFb.Prog1,TTTGATCTCGGCTCTT_Hyp1,TTTGGAGAGCTGTTAC_Hb2,TTTGGTTCATTCTCTA_Hb1,TTTGGTTTCTTCACAT_vFb.Prog1,TTTGTTGCAACTAGAA_vFb.Prog2,TTTGTTGCAAGGCGTA_vFb.Prog2,TTTGTTGCACTATGTG_vFb.Prog2,TTTGTTGGTACCGGAA_Hyp3
RERG,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ENSDARG00000100660,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
syn3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ptpro,0,0,0,0,1,0,0,0,0,0,...,0,0,2,0,0,0,1,1,0,0
eps8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
tbk1,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
gpr19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
crebl2,0,0,0,0,0,0,0,0,2,2,...,0,0,1,0,0,0,0,0,0,0
dusp16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
lrp6,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

# 3. Load data
- Now we replace the zebrafish gene names with their mouse homologs.
- Duplicated zebrafish genes, will be summed up (e.g. pax6a+pax6b = Pax6)

In [4]:
homology_zf_mouse_df[0:10]

           zf_gene_id  zf11_gene mouse_gene  zf10_gene
0  ENSDARG00000077004    aldh1l1    Aldh1l1    aldh1l1
1  ENSDARG00000100591      sox32        Sry      sox32
2  ENSDARG00000013921       frya        Fry       frya
3  ENSDARG00000094752     rpe65b      Rpe65     rpe65b
4  ENSDARG00000006399     ywhae1      Ywhae     ywhae1
5  ENSDARG00000005141     camkvb      Camkv     camkvb
6  ENSDARG00000019747     hsd3b2     Hsd3b4     hsd3b2
7  ENSDARG00000093235       mpst        Tst        TST
8  ENSDARG00000059616     hs3st2     Hs3st2     hs3st2
9  ENSDARG00000099149  hs3st3b1a   Hs3st3b1  hs3st3b1a

In [5]:
#zf vs mouse
homology_zf_mouse_dict = dict(zip(homology_zf_mouse_df["zf10_gene"], homology_zf_mouse_df["mouse_gene"]))

- Filter for genes that exist in the homology dict (i.e., have a match)

In [6]:
zf_mouse_genes_with_homologs = expr_df.index.intersection(homology_zf_mouse_dict.keys())
expr_df_zf_mouse_filtered = expr_df.loc[zf_mouse_genes_with_homologs]

- Rename zebrafish genes to mouse homologs and sum up the expression values of duplicates

In [7]:
expr_df_zf_mouse_renamed = expr_df_zf_mouse_filtered.rename(index=homology_zf_mouse_dict)
expr_df_zf_mouse_renamed = expr_df_zf_mouse_renamed.groupby(expr_df_zf_mouse_renamed.index).sum()

- Check renamed expression matrix

In [8]:
expr_df_zf_mouse_renamed[0:10]

,AAACCCACACTCCGGA_Hyp3,AAACCCATCTACTATC_Hb3,AAACGAAAGGCTTCCG_PrT,AAACGAACAAGTGCAG_pTub,AAACGAAGTCTCGGGT_vFb.Prog2,AAACGCTTCCCAGGCA_Hyp1,AAAGAACCAGAGTTCT_Cb,AAAGAACTCCATCGTC_vFb.Prog1,AAAGAACTCGAACGGA_vFb.Prog2,AAAGGATCACGACAGA_vFb.Prog2,...,TTTGATCCACGGTGAA_Hyp3,TTTGATCTCGCTTGAA_vFb.Prog1,TTTGATCTCGGCTCTT_Hyp1,TTTGGAGAGCTGTTAC_Hb2,TTTGGTTCATTCTCTA_Hb1,TTTGGTTTCTTCACAT_vFb.Prog1,TTTGTTGCAACTAGAA_vFb.Prog2,TTTGTTGCAAGGCGTA_vFb.Prog2,TTTGTTGCACTATGTG_vFb.Prog2,TTTGTTGGTACCGGAA_Hyp3
1110004F10Rik,0,0,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1110038F14Rik,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1110059G10Rik,0,0,0,0,1,3,0,0,0,2,...,0,0,0,0,1,0,1,0,0,0
1500009L16Rik,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1700017B05Rik,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1700019D03Rik,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1700025G04Rik,0,0,0,0,1,2,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1700030J22Rik,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1700067K01Rik,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1700088E04Rik,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

# 4. Save renamed gene expression matrix

In [9]:
expr_df_zf_mouse_renamed.to_csv(r"D:\scRNAseq\10X\DA136\SeuratAnalysis_2024-09-03\MapMyCells\MapMyCells_input_data\modified_expression_matrix_mousenames.csv")

# 5. Session info

In [10]:
session_info.show()